In [8]:
import numpy as np 
a=np.zeros(9)
print(a)
print(type(a[0]))  #float
print(a.shape)   #--->(row i.e axis 0 , first axis,column i.e axis 1 i.e secound axis)
#axis means the dimension of the array. lmao
a.shape=(9,1)
print(a)



[0. 0. 0. 0. 0. 0. 0. 0. 0.]
<class 'numpy.float64'>
(9,)
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]


Dimension of array

In [11]:
np.ndim(a)    #element is defined by row and column thus 2 dimension.
np.size(a)    #product of elements of shape

9

Example

In [18]:
a=np.arange(15).reshape(3,5)
print(a)
a.shape   #shape
a.ndim #dimension
print(a.itemsize)   #element size in bytesi.e 8 bits =1 byte
b=np.array([4,5,6])


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
4


In [22]:
#you can create an array from regular Python list or tuple 
#using array function
a=np.arange(10,50,4)
print(a)
b=np.zeros((3,4,5)) #3 stacks of 4x5 2d array
print(b)

[10 14 18 22 26 30 34 38 42 46]
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [30]:
#linespace
# np.linespace(0,2,9)
print(np.linspace(0,2,9))
print(np.arange(0,9,2))
x=np.arange(0,9,2)
for ele in x:print(ele)


from numpy import pi
x=np.linspace(0,2*pi,100)
np.sin(x)


[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]
[0 2 4 6 8]
0
2
4
6
8


array([ 0.00000000e+00,  6.34239197e-02,  1.26592454e-01,  1.89251244e-01,
        2.51147987e-01,  3.12033446e-01,  3.71662456e-01,  4.29794912e-01,
        4.86196736e-01,  5.40640817e-01,  5.92907929e-01,  6.42787610e-01,
        6.90079011e-01,  7.34591709e-01,  7.76146464e-01,  8.14575952e-01,
        8.49725430e-01,  8.81453363e-01,  9.09631995e-01,  9.34147860e-01,
        9.54902241e-01,  9.71811568e-01,  9.84807753e-01,  9.93838464e-01,
        9.98867339e-01,  9.99874128e-01,  9.96854776e-01,  9.89821442e-01,
        9.78802446e-01,  9.63842159e-01,  9.45000819e-01,  9.22354294e-01,
        8.95993774e-01,  8.66025404e-01,  8.32569855e-01,  7.95761841e-01,
        7.55749574e-01,  7.12694171e-01,  6.66769001e-01,  6.18158986e-01,
        5.67059864e-01,  5.13677392e-01,  4.58226522e-01,  4.00930535e-01,
        3.42020143e-01,  2.81732557e-01,  2.20310533e-01,  1.58001396e-01,
        9.50560433e-02,  3.17279335e-02, -3.17279335e-02, -9.50560433e-02,
       -1.58001396e-01, -

In [31]:
np.set_printoptions(threshold=sys.maxsize) 

TypeError: zeros() takes from 1 to 3 positional arguments but 4 were given

Baisc operations

random generator

In [33]:
A=np.array([[1,2],[3,4]])
B=np.array([[4,5],[7,8]])
print(A*B)  #elementwise multiplication
print(A@B)   #matrix multiplication


[[ 4 10]
 [21 32]]
[[18 21]
 [40 47]]


In [3]:
import numpy as np
rg=np.random.default_rng(3)   #(1) here ensures that if you run the block n times the set of numbers wilbe same
print(rg.random((1,5)))
print(rg.random((1,5)))

[[0.08564917 0.23681051 0.80127447 0.58216204 0.09412864]]
[[0.43312694 0.4790513  0.15973891 0.73457715 0.11367202]]


In [8]:
x=np.random.rand(4,5)
x.reshape((20,1))


array([[0.42023583],
       [0.56253384],
       [0.06749029],
       [0.15234044],
       [0.93561107],
       [0.80434593],
       [0.39522206],
       [0.07200755],
       [0.3860757 ],
       [0.27877274],
       [0.54630624],
       [0.74379212],
       [0.54240027],
       [0.07515959],
       [0.27774054],
       [0.68971562],
       [0.63025019],
       [0.60216364],
       [0.95760729],
       [0.51032365]])

In [20]:
x=np.zeros((2,3,4,5))
import sys
np.set_printoptions(threshold=sys.maxsize) 
import matplotlib.pyplot as plt
fname=plt.imread('2.png')
fname.shape

(28, 28, 4)

In [19]:
import numpy as np
z=np.array([ele for ele in range(24)]).reshape((2,3,4))
print('z as an 3d image is ')
print(z)

print('dimension 0',z[0,:,:])
print('dim 1',z[1,:,:])
# print('dim 2',z[:,:,2])


# print(z)
# print(z.shape)
# print('sum along axis 0',z.sum(axis=1))
# znew=z.sum(axis=0)
# print('sum along axis 0 again',znew.sum(axis=1))

z as an 3d image is 
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
dimension 0 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
dim 1 [[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
